# Copyright 2019 Tampere University
# This software was developed as a part of the CityIoT project: https://www.cityiot.fi/english
# This source code is licensed under the 3-clause BSD license. See license.txt in the repository root directory.
# Author(s): Mikko Nurminen <mikko.nurminen@tuni.fi>

# copied and modified with instructions from:
# https://github.com/ging/fiware-idm/tree/master/extras/docker
# and
# https://github.com/Fiware/tutorials.PEP-Proxy/blob/master/docker-compose/orion.yml
#
# Docker Hub tags have been chosen to reflect FIWARE release 7.5.1 as specified in
# https://github.com/Fiware/catalogue/releases, or later versions where required

version: "3"

volumes:
  vol-mysql:
  vol-mongo:

services:
  mysql-keyrock:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - vol-mysql:/var/lib/mysql
    environment:
      # Change these settings to your liking
      - MYSQL_ROOT_PASSWORD=idm_root_password
      - MYSQL_DATABASE=idm_db # Must be the same as in - IDM_DB_NAME
      - MYSQL_USER=idm_user # Must be the same as in - IDM_DB_USER
      - MYSQL_PASSWORD=idm_users_password # Must be the same as in - IDM_DB_PASS

  keyrock-idm:
    image: fiware/idm:FIWARE_7.7
    # Remember: Either specify both ports (HOST:CONTAINER), or
    # just the container port (a random host port will be chosen).
    ports:
      # keep this port in sync this port with keyrock_config.js config.port and IDM_PORT
      - "3005:3005"
      - "443:443"
    depends_on:
      - mysql-keyrock
    environment:
      - IDM_DB_HOST=mysql-keyrock
      - IDM_DB_PASS=idm_users_password
      - IDM_DB_USER=idm_username
      - IDM_DB_NAME=idm_db
      - IDM_DIALECT=mysql
      - IDM_DB_PORT=3306
      - IDM_SESSION_SECRET=ENTER_RANDOM_STRING_HERE
      - IDM_ENCRYPTION_KEY=NTER_RANDOM_STRING_HERE
      - IDM_PORT=3005
      - IDM_HTTPS_ENABLED=false
      - IDM_ADMIN_USER=tester-admin
      - IDM_ADMIN_EMAIL=tester-admin@tester.com
      - IDM_ADMIN_PASS=tester-2020
      - IDM_USAGE_CONTROL_ENABLED=false
    volumes:
      - ./config/keyrock7.7_config.js:/opt/fiware-idm/config.js

  # This Wilma will proxy Orion
  # Application representing Orion needs to be setup in Keyrock.
  # See the basic access control README.md for details.
  wilma-proxy:
    image: fiware/pep-proxy:FIWARE_7.7
    depends_on:
      - keyrock-idm
    ports:
      - "1027:1027"
    expose:
      - "1027"
    environment:
      - PEP_PROXY_PORT=1027
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_IDM_HOST=keyrock-idm
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_APP_HOST=orion
      - PEP_PROXY_APP_PORT=1026
      - PEP_PROXY_ORG_ENABLED=false
      - PEP_PROXY_ORG_HEADER=fiware-service
      - PEP_PROXY_APP_ID=ENTER_ORION_APP_ID_FROM_KEYROCK # For help on getting this value, read the README.md
      - PEP_PROXY_USERNAME=ENTER_PEP_PROXY_USERNAME_FROM_KEYROCK # For help on getting this value, read the README.md
      - PEP_PASSWORD=ENTER_PEP_PROXY_PASSWORD_FROM_KEYROCK # For help on getting this value, read the README.md
      - PEP_PROXY_MAGIC_KEY=ENTER_RANDOM_STRING_HERE
      - PEP_TOKEN_SECRET=ENTER_RANDOM_STRING_HERE
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_PDP=idm
    volumes:
      - ./config/wilma7.7_config.js:/opt/fiware-pep-proxy/config.js

  mongodb-orion:
    image: mongo:latest
    volumes:
      - vol-mongo:/data
    expose:
      - "27017"
    command: --smallfiles

  orion:
    image: fiware/orion:latest
    depends_on:
      - mongodb-orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb-orion
    healthcheck:
      test: curl --fail -s http://localhost:1026/version || exit 1
